version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    volumes:
      - ./inputdata:/csvserver/inputdata
    ports:
      - "9393:9300"
    env_file:
      - ./csvserver.env

  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
